web/api/urls.py
from rest_framework_simplejwt import views as simplejwt
from django.urls import path

from . import views

urlpatterns = [
    path('token/', simplejwt.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', simplejwt.TokenRefreshView.as_view(), name='token_refresh'),

    path('task/result', views.ApiTaskView.as_view(), name='api-task-result'),
    path('task/generic_run', views.run_task, name="run_task"),
    path('task/run_and_store', views.ApiScriptStoreView.as_view(), name='api-task-run'),
    path('script/run', views.ApiScriptView.as_view(), name='api-script-run'),
    path('files', views.ApiFileView.as_view(), name='api-files'),
]

web/frontend/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'frontend'
urlpatterns = [
    path('', views.index, name='index'), 
    path('refresh_graph', views.refresh, name='refresh_graph'),
    path('about/', views.about, name='about'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('docs/', views.docs, name='docs'),
    path('docs/<int:doc_id>', views.doc_view, name='doc_view'),
    path('docs/create/', views.doc_create, name='doc_create'),

    path('peers/', views.peers, name='peers'),
    path('peers/<int:peer_id>', views.peer_view, name='peer_view'),
    path('peers/create/', views.peer_create, name='peer_create'),

    path('files/', views.files, name='files'),
    path('files/create/', views.create_file, name='file_create'),
    path('files/list', views.list_files, name='file_list'),
    path('files/view/<str:filename>', views.view_file, name='file_view'),

    path('tasks/', views.prepare_task, name="tasks"),
    path('tasks/<str:task_id>', views.show_task_result, name="show_task"),
]

web/web/urls.py
from django.urls import path
from django.conf.urls import include
from django.views.generic.base import RedirectView
from django.contrib import admin


urlpatterns = [
    path('frontend/admin/', admin.site.urls),
    path('hello/', include('hello.urls')),
    path('scripts/', include('scripts.urls')),
    path('storage/', include('storage.urls')),
    path('pinger/', include('pinger.urls')),
    path('calc/', include('calculator.urls')),
    path('api/', include('api.urls')),
    path('frontend/', include('frontend.urls')),

    path('', RedirectView.as_view(url='/frontend', permanent=True), name='index')

]

web/scripts/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

OS_CHOICES = [
    ('windows', 'Windows'),
    ('linux', 'Linux'),
]

class Doc(models.Model):
    DOC_TYPES = [
        ('sh', 'Bash'),
        ('py', 'Python'),
    ]

    name = models.CharField(max_length=20)
    content = models.TextField(blank=True)
    type = models.CharField(max_length=3, choices=DOC_TYPES)
    created = models.DateTimeField(editable=False, default=timezone.now)
    modified = models.DateTimeField(editable=False, auto_now=True)
    os = models.CharField(help_text='Operating System', choices=OS_CHOICES, max_length=7)



class Peer(models.Model):

    ip_address = models.GenericIPAddressField(null=True)
    ssh_port = models.IntegerField(default=22)
    hostname = models.CharField(unique=True, max_length=50)
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    private_key = models.TextField(null=True)
    passphrase = models.CharField(blank=True, default="", max_length=20)
    os = models.CharField(help_text='Operating System', choices=OS_CHOICES, max_length=7)

web/frontend/forms.py
from django import forms
from celery import current_app 

from scripts import models as scripts

# get a list of availabel tasks and store them in a tuple for a dropdown in frontend
# ignore interal celery tasks
AVAILABLE_TASKS = [tuple([t, t]) for t in current_app.tasks.keys() if not t.startswith('celery')]

class DocForm(forms.ModelForm):
    class Meta:
        model = scripts.Doc
        fields = '__all__'

class PeerForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    passphrase = forms.CharField(widget=forms.PasswordInput(), required=False)
    class Meta:
        model = scripts.Peer
        fields = '__all__'

class FileForm(forms.Form):
    filename = forms.CharField(error_messages={'required': 'Please enter a filename'})
    content = forms.CharField(widget=forms.Textarea())

class FileViewForm(forms.Form):
    filename = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    content = forms.CharField(widget=forms.Textarea())

class TaskForm(forms.Form):
    taskname = forms.CharField(label="Choose a task from the list!", widget=forms.Select(choices=AVAILABLE_TASKS), initial="hello.say_hello")
    kwargs = forms.JSONField(initial={}, required=False)

class TaskResultForm(forms.Form):
    result = forms.CharField(widget=forms.Textarea(attrs={'readonly':'readonly'}))

web/templates/about.html
{% extends 'base.html' %} {% block content %} {% load static %}

<style>
    .container img {
        display: block;
        margin: auto;
        height: auto;
        max-height: 100%;
        width: auto;
        max-width: 100%;
    }
</style>

<div class="container">
    <img src="{%  static 'automatic_umbrella_architektur.svg' %}" alt="System architecture">
</div>
{% endblock %}

web/templates/base.html
{% load static %}
<script type="text/javascript" src="https://code.jquery.com/jquery-1.7.1.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Automatic Umbrella</title>
    <link rel="shortcut icon" type="image/png" href="{%  static 'icons/favicon.ico' %}" />
    <script>
        var script = document.createElement('script');
        script.src = 'https://code.jquery.com/jquery-3.4.1.min.js';
        script.type = 'text/javascript';
        document.getElementsByTagName('head')[0].appendChild(script);
    </script>
    <style>
        .icon {
            width: 80px;
        }
        
        body {
            margin: 0;
            font-family: Arial, Helvetica, sans-serif;
            background-color: #DCDCDC;
        }
        
        .topnav {
            overflow: hidden;
            background-color: #333;
        }
        
        .topnav a {
            float: left;
            color: #f2f2f2;
            text-align: center;
            padding: 20px 20px;
            text-decoration: none;
            font-size: 20px;
        }
        
        .topnav a:hover {
            background-color: #ddd;
            color: black;
        }
        
        .topnav a.active {
            background-color: #ffffff;
            color: white;
        }
        
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }
        
        td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }
        
        th {
            color: white;
            background: #333;
            text-align: left;
            padding: 8px;
        }
        
        tr:nth-child(odd) {
            background-color: #CBDFEB;
        }
        
        tr:nth-child(even) {
            background-color: #dddddd;
        }
    </style>
</head>

<body>

    <div class="topnav">
        <!--<a class="active" href="{% url 'frontend:index' %}">
            <img alt="AutomaticUmbrella" src="{%  static 'icons/favicon.svg' %}" width="50"></a>
        -->
        <a href="{% url 'frontend:index' %}">Home</a>
        <a href="{% url 'frontend:peers' %}">Peers</a>
        <a href="{% url 'frontend:docs' %}">Docs</a>
        <a href="{% url 'frontend:files' %}">Files</a>
        <a href="{% url 'frontend:tasks' %}">Tasks</a>
        <a href="{% url 'frontend:about' %}">About</a> {% if user.is_staff %}
        <a href="/frontend/admin">Admin</a> {% endif %} {% if user.is_authenticated %}
        <a href="{% url 'frontend:logout' %}">Logout</a> {% endif %}
    </div>
    {% block content %}{% endblock content %}
</body>

</html>

web/templates/base_view.html
{% extends 'base.html' %} {% block content %}
<div style="padding-left:16px">
</div>
<div>
    <form method="post">
        {% csrf_token %} {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
</div>

{% endblock %}

web/templates/create_doc.html
{% extends 'base.html' %} {% block content %}

<form method="post">
    <div class="form-group">
        {{ form.name.errors }}
        <label for="{{ form.name.id_for_label }}">Name</label>
        <input type="text" value="{{ form.name.value|default_if_none:'' }}" class="form-control" name="name" placeholder="Enter name" id="id_name">
    </div>

    <div class="form-group">
        {{ form.content.errors }}
        <label for="{{ form.content.id_for_label }}">Content</label>
        <textarea id="id_content" class="form-control" name="content" placeholder="ls" rows="10">{{ form.content.value|default_if_none:"" }}</textarea>
    </div>

    <div class="form-group">
        {{ form.type.errors }}
        <label for="{{ form.type.id_for_label }}">Type</label> <select class="form-control" name="type" id="id_type">
            {% if form.instance.type == "py" %}
                <option value="sh">Bash</option>
                <option value="py" selected>Python</option>
            {% else %}
                <option value="sh" selected>Bash</option>
                <option value="py">Python</option>
            {% endif %}
        </select>
    </div>
    <div class="form-group">
        {{ form.os.errors }}
        <label for="{{ form.os.id_for_label }}">Operating System</label> <select id="id_os" class="form-control" name="os">
            {% if form.instance.os == "windows" %}
                <option value="windows" selected>Windows</option>
                <option value="linux">Linux</option>
            {% else %}
            <option value="windows">Windows</option>
            <option value="linux" selected>Linux</option>
            {% endif %}
        </select>
    </div>
    <div>
        <input type="submit" value="Save">
    </div>

</form>

{% endblock %}

web/templates/create_file.html
{% extends 'base.html' %} {% block content %}

<form method="post">
    <div class="form-group">
        {{ form.filename.errors }}
        <label for="{{ form.filename.id_for_label }}">Filename</label>
        <input type="text" value="{{ form.filename.value|default_if_none:'' }}" class="form-control" name="filename" placeholder="Enter filename" id="id_filename">
    </div>

    <div class="form-group">
        {{ form.content.errors }}
        <label for="{{ form.content.id_for_label }}">Content</label>
        <textarea name="content" rows="20" class="form-control" id="id_content" placeholder="Enter content">{{ form.content.value|default_if_none:"" }}</textarea>
    </div>

    <div>
        <input type="submit" value="Save">
    </div>
</form>

{% endblock %}

web/templates/create_peer.html
{% extends 'base.html' %} {% block content %}

<form method="post">
    <div class="form-group">
        {{ form.ip_address.errors }}
        <label for="{{ form.ip_address.id_for_label }}">IP address</label>
        <input type="text" value="{{ form.ip_address.value|default_if_none:'' }}" class="form-control" name="ip_address" placeholder="Enter IP address" id="id_ip_address">
    </div>

    <div class="form-group">
        {{ form.ssh_port.errors}}
        <label for="{{ form.ssh_port.id_for_label }}">SSH port</label>
        <input type="number" name="ssh_port" value="{{ form.ssh_port.value|default_if_none:'22' }}" class="form-control" required id="id_ssh_port">
    </div>

    <div class="form-group">
        {{ form.hostname.errors }}
        <label for="{{ form.hostname.id_for_label">Hostname</label>
        <input type="text" name="hostname" maxlength="50" value="{{ form.hostname.value|default_if_none:'' }}" required id="id_hostname" class="form-control" placeholder="Enter hostname">
    </div>

    <div class="form-group">
        {{ form.username.errors }}
        <label for="{{ form.username.id_for_label">Username</label>
        <input type="text" name="username" maxlength="20" value="{{ form.username.value|default_if_none:'' }}" required id="id_username" class="form-control" placeholder="Enter username">
    </div>

    <div class="form-group">
        {{ form.password.errors }}
        <label for="{{ form.password.id_for_label }}">Password</label>
        <input type="password" name="password" class="form-control" value="{{ form.password.value|default_if_none:'' }}" id="id_password" placeholder="Enter password">
    </div>

    <div class="form-group">
        {{ form.private_key.errors }}
        <label for="{{ form.private_key.id_for_label }}">Private key</label>
        <textarea name="private_key" rows="5" class="form-control" id="id_private_key">{{ form.private_key.value|default_if_none:"" }}</textarea>
    </div>

    <div class="form-group">
        {{ form.passphrase.errors }}
        <label for="form.passphrase.label_for_id">Passphrase</label>
        <input type="password" name="passphrase" class="form-control" value="{{ form.passphrase.value|default_if_none:'' }}" placeholder="Enter passphrase" id="id_passphrase">
    </div>

    <div class="form-group">
        {{ form.os.errors }}
        <label for="{{ form.os.id_for_label }}">Operating System</label> <select id="id_os" class="form-control" name="os">
            {% if form.instance.os == "windows" %}
                <option value="windows" selected>Windows</option>
                <option value="linux">Linux</option>
            {% else %}
            <option value="windows">Windows</option>
            <option value="linux" selected>Linux</option>
            {% endif %}
        </select>
    </div>

    <div>
        <input type="submit" value="Save">
    </div>
</form>

{% endblock %}

web/templates/files.html
{% extends 'base.html' %} {% block content %} {% load static %}
<script type="text/javascript" src="https://code.jquery.com/jquery-1.7.1.min.js"></script>
<script>
    function get_file() {
        let filename = document.getElementById("filename_input").value;
        var url = "{% url 'frontend:file_view' filename=0 %}".replace('0', filename.toString())
        document.location.href = url
    }

    function showFileSearchForm() {
        document.getElementById("view_file_div").style.display = "block"
    }
</script>

<style>
    * {
        box-sizing: border-box
    }
    
    #result_button {
        display: none;
    }
    
    .tab {
        float: left;
        border: 1px solid #ccc;
        background-color: #f1f1f1;
        width: 30%;
        height: 300px;
    }
    /* Style the buttons inside the tab */
    
    .tab button {
        display: block;
        background-color: inherit;
        color: black;
        padding: 22px 16px;
        width: 100%;
        border: none;
        outline: none;
        text-align: left;
        cursor: pointer;
        transition: 0.3s;
        font-size: 17px;
    }
    /* Change background color of buttons on hover */
    
    .tab button:hover {
        background-color: #ddd;
    }
    /* Create an active/current "tab button" class */
    
    .tab button.active {
        background-color: #ccc;
    }
    /* Style the tab content */
    
    .tabcontent {
        float: left;
        padding: 0px 12px;
        border: 1px solid #ccc;
        width: 70%;
        border-left: none;
        height: 300px;
    }
    
    #view_file_div {
        display: none;
    }
</style>

<div style="padding-left:16px">
    <h2>Files</h2>
</div>

<div>
    Files are located in an external store. To safe you some time, we don't load all the files from the storage. <br> You can either request a list of all files or request the content of a specific one. Of course it is also possibile to create a new file.
    <br>
</div>
<br>
<div class="tab" id="file_buttons">
    <form>
        <button class="tablinks" id="list_files_button" formaction="{% url 'frontend:file_list' %}">List all files</button>
    </form>
    <button class="tablinks" id="view_file_button" onclick="showFileSearchForm()">View file</button>
    <form>
        <button class="tablinks" id="create_file_button" formaction="{% url 'frontend:file_create' %}">Create new file</button>
    </form>
</div>

<div class="tabcontent">
    <div id="view_file_div">
        <form class="tablinks" id='filename_form' method="get">
            File: <input id='filename_input' type="text" name="file" id="file">
        </form>
        <button id='getFile_button' onclick="get_file()">View file</button>
    </div>
</div>





{% endblock %}

web/templates/files_list.html
{% extends 'base.html' %} {% block content %} {% load static %}
<script type="text/javascript" src="https://code.jquery.com/jquery-1.7.1.min.js"></script>
<script>
    $(document).on("click", ".file_load_button", function() {
        let filename = $(this).text();;
        console.log(filename);

        var url = "{% url 'frontend:file_view' filename=0 %}".replace('0', filename.toString())
        document.location.href = url
    });
</script>

<div style="padding-left:16px">
    <h2>Files</h2>
</div>
<div>
    <table>
        <tr>
            <th>Name</th>
            <th>Modified</th>
            <th>Content type</th>
            <th>Size</th>
            <th>Version ID</th>
        </tr>
        {% for file in result %}
        <tr>
            <td>
                <button class="file_load_button">{{ file.object_name }}</button>
            </td>
            <td> {{ file.last_modified }}</td>
            <td> {{ file.content_type }}</td>
            <td> {{ file.size }} </td>
            <td> {{ file.version_id }} </td>
        </tr>
        {% endfor %}
    </table>
</div>

{% endblock %}

web/templates/home.html
{% extends 'base.html' %} {% block content %} {% load static %}

<script>
    function refreshImage() {
        window.location.href = "{% url 'frontend:refresh_graph' %}";
    }
</script>

<style>
    .container img {
        display: block;
        margin: auto;
        height: auto;
        max-height: 100%;
        width: auto;
        max-width: 100%;
    }
</style>

<div>
    <button onclick="refreshImage()">Refresh</button>
</div>

<div class="container">
    <img src="{%  static 'docker-graph.svg' %}" alt="Docker Network Graph">
</div>
{% endblock %}

web/templates/list_tasks.html
{% extends 'base.html' %} {% block content %} {% for task in tasks %}
<div class="form-group">
    <a href="{% url 'frontend:prepare_task' task %}">{{ task }}</a>
</div>
{% endfor %} {% endblock %}

web/templates/peers.html
{% extends 'base.html' %} {% block content %} {% load static %}
<div style="padding-left:16px">
    <h2>Peers</h2>
</div>
<div>
    <a href="{% url 'frontend:peer_create' %}">Add peer</a>
</div>
<div>
    <table>
        <tr>
            <th>ID</th>
            <th>Hostname</th>
            <th>IP-Address</th>
            <th>Username</th>
            <th>SSH-Port</th>
            <th>OS</th>
        </tr>
        {% for peer in result %}
        <tr>
            <td> {{ peer.pk }}</td>
            <td>
                <a href="{% url 'frontend:peer_view' peer.pk %}">
                    {{ peer.hostname }}</a>
            </td>
            <td> {{ peer.ip_address }}</td>
            <td> {{ peer.username }}</td>
            <td> {{ peer.ssh_port }}</td>
            <td> {{ peer.get_os_display }} </td>
        </tr>
        {% endfor %}
    </table>
</div>

{% endblock %}

web/templates/start_task.html
{% extends 'base.html' %} {% block content %}
<script>
    var task_url = "{{ API_URL }}" + "/api/task/generic_run"

    function showForm() {
        var selection = document.getElementById("id_taskname");
        $('div[name="choice"]').hide()
        var taskname = selection.value;
        console.log(taskname)
        document.getElementById(taskname).style = "display: block;";
    }

    function runTask() {
        var selection = document.getElementById("id_taskname");
        var taskname = selection.value;
        var jsonData = {
            "taskname": taskname
        };
        var childInputs = document.getElementById(taskname).getElementsByTagName('input');
        var childAreas = document.getElementById(taskname).getElementsByTagName('textarea');
        var childs = [...childInputs, ...childAreas];

        for (i = 0; i < childs.length; i++) {
            if (childs[i].name == "peers") {
                peers = childs[i].value.split(",");
                jsonData[childs[i].name] = peers.map(Number);
                continue
            }
            if (isNaN(childs[i].value)) {
                jsonData[childs[i].name] = childs[i].value;
            } else {
                jsonData[childs[i].name] = parseInt(childs[i].value)
            }
        }
        console.log(jsonData)


        $.ajax({
            type: "POST",
            url: task_url,
            data: JSON.stringify(jsonData),
            dataType: "json",
            success: function(data, textStatus, request) {
                var task = data.task_id;
                console.log(task)
                window.location.href = "/frontend/tasks/" + task;
            },
            error: function(data, textStatus, request) {
                console.log("error")
            }
        });
    }
</script>
<style>
    .form-group {
        display: none;
    }
</style>

<form>
    <div class="form-group" style="display: block;">
        {{ form.taskname.errors }}
        <label for="{{ form.taskname.id_for_label }}">Task</label>
        <select id="id_taskname" class="form-control" name="taskname" onchange="if (this.selectedIndex) showForm();">
            <option value="-1">Choose a task</option>
            {% for short, long in form.taskname.field.widget.choices %}
            <option value="{{ short }}"{% if form.initial.taskname == short %} selected {% endif %}>
                {{ long }}
            </option>
            {% endfor %}
        </select>
    </div>

    <div class="form-group" id="scripts.run_script" name="choice">
        <label>Doc by ID</label>
        <input type="number" name="doc_id" required id="run_script_id_doc" class="form-control" placeholder="Enter doc id">
        <label>Peers by ID (Comma separated)</label>
        <input type="text" name="peers" required id="run_script_id_peers" class="form-control" placeholder="Enter peers">
    </div>

    <div class="form-group" id="hello.say_hello" name="choice">
        <label>Your name</label>
        <input type="text" name="name" required id="id_name" class="form-control" placeholder="Enter your name">
    </div>

    <div class="form-group" id="hello.run_script_output_to_storage" name="choice">
        <label>Doc by ID</label>
        <input type="number" name="doc_id" required id="run_script_output_to_storage_id_doc" class="form-control" placeholder="Enter doc id">
        <label>Peers by ID (Comma separated)</label>
        <input type="text" name="peers" required id="run_script_output_to_storage_id_peers" class="form-control" placeholder="Enter peers">
        <label>Filename</label>
        <input type="text" name="filename" required id="run_script_output_to_storage_id_filename" class="form-control" placeholder="Enter filename">
    </div>

    <div class="form-group" id="pinger.ping_host" name="choice">
        <label>IP address</label>
        <input type="text" name="host" required id="ping_host_id_host" class="form-control" placeholder="Enter IP address">
        <label>Timeout</label>
        <input type="number" name="timeout" id="ping_host_id_timeout" class="form-control" placeholder="2">
    </div>

    <div class="form-group" id="pinger.discover" name="choice">
        <label>Subnet (CIDR)</label>
        <input type="text" name="subnet" required id="discover_id_host" class="form-control" placeholder="Enter IP address">
        <label>Timeout</label>
        <input type="number" name="timeout" id="discover_id_timeout" class="form-control" placeholder="2">
    </div>

    <div class="form-group" id="calc.estimate_pi" name="choice">
        <label>Interval</label>
        <input type="number" name="interval" id="estimate_pi_id_interval" class="form-control" placeholder="1000">
    </div>

    <div class="form-group" id="storage.put_content" name="choice">
        <label>Filename</label>
        <input type="text" name="filename" required id="put_content_id_filename" class="form-control" placeholder="Enter filename">
        <label>Content</label>
        <textarea name="content" required rows="20" class="form-control" id="put_content_id_content"></textarea>
    </div>

    <div class="form-group" id="storage.get_content" name="choice">
        <label>Filename</label>
        <input type="text" name="filename" required id="get_content_id_filename" class="form-control" placeholder="Enter filename">
    </div>

    <div class="form-group" id="storage.put_file" name="choice">
        <label>Filename</label>
        <input type="text" name="filename" required id="put_file_id_filename" class="form-control" placeholder="Enter filename">
        <label>Filepath</label>
        <input type="text" name="filename" required id="put_file_id_filepath" class="form-control" placeholder="Enter filepath">
    </div>

    <div class="form-group" id="storage.list_files" name="choice">
    </div>

    <div class="form-group" id="monitor.build_network_graph" name="choice">
    </div>

    <div>
        <br>
        <input type="submit" value="Run task" onclick="runTask()">
    </div>
</form>
{% endblock %}

web/templates/task_children_list.html
{% extends 'base.html' %} {% block content %} {% load static %}
<div style="padding-left:16px">
    <h2>Children of Task {{ origin }}</h2>
</div>
<div>
    <table>
        <tr>
            <th>Task ID</th>
            <th>Name</th>
            <th>args</th>
            <th>kwargs</th>
            <th>Status</th>
            <th>Worker</th>
            <th>Date done</th>
        </tr>
        {% for child in children %}
        <tr>
            <td>
                <a href="{% url 'frontend:show_task' child.task_id %}">{{ child.task_id }}</a>
            </td>
            <td> {{ child.name }} </td>
            <td> {{ child.args }} </td>
            <td> {{ child.kwargs }} </td>
            <td> {{ child.status }} </td>
            <td> {{ child.worker }} </td>
            <td> {{ child.date_done }} </td>
        </tr>
        {% endfor %}
    </table>
</div>

{% endblock %}

web/templates/task_result.html
{% extends 'base.html' %} {% block content %}
<div style="padding-left:16px">
</div>
<div class="form-group">
    {{ form.result.errors }}
    <label for="{{ form.result.id_for_label }}">Result</label>
    <textarea name="result" rows="20" class="form-control" id="id_result">{{ form.result.value|default_if_none:"" }}</textarea>
</div>

{% endblock %}